// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FetchUserByIDHandlerFunc turns a function with the right signature into a fetch user by ID handler
type FetchUserByIDHandlerFunc func(FetchUserByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FetchUserByIDHandlerFunc) Handle(params FetchUserByIDParams) middleware.Responder {
	return fn(params)
}

// FetchUserByIDHandler interface for that can handle valid fetch user by ID params
type FetchUserByIDHandler interface {
	Handle(FetchUserByIDParams) middleware.Responder
}

// NewFetchUserByID creates a new http.Handler for the fetch user by ID operation
func NewFetchUserByID(ctx *middleware.Context, handler FetchUserByIDHandler) *FetchUserByID {
	return &FetchUserByID{Context: ctx, Handler: handler}
}

/*FetchUserByID swagger:route GET /users/{id} Users fetchUserById

Возвращает данные пользователя по ID.

Возвращает данные пользователя по ID

*/
type FetchUserByID struct {
	Context *middleware.Context
	Handler FetchUserByIDHandler
}

func (o *FetchUserByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFetchUserByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
