// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/i-iterbium/cyber-engine/models"
)

// FetchUserByIDOKCode is the HTTP code returned for type FetchUserByIDOK
const FetchUserByIDOKCode int = 200

/*FetchUserByIDOK OK

swagger:response fetchUserByIdOK
*/
type FetchUserByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewFetchUserByIDOK creates FetchUserByIDOK with default headers values
func NewFetchUserByIDOK() *FetchUserByIDOK {

	return &FetchUserByIDOK{}
}

// WithPayload adds the payload to the fetch user by Id o k response
func (o *FetchUserByIDOK) WithPayload(payload *models.User) *FetchUserByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fetch user by Id o k response
func (o *FetchUserByIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FetchUserByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FetchUserByIDBadRequestCode is the HTTP code returned for type FetchUserByIDBadRequest
const FetchUserByIDBadRequestCode int = 400

/*FetchUserByIDBadRequest Переданы некорректные данные

swagger:response fetchUserByIdBadRequest
*/
type FetchUserByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFetchUserByIDBadRequest creates FetchUserByIDBadRequest with default headers values
func NewFetchUserByIDBadRequest() *FetchUserByIDBadRequest {

	return &FetchUserByIDBadRequest{}
}

// WithPayload adds the payload to the fetch user by Id bad request response
func (o *FetchUserByIDBadRequest) WithPayload(payload *models.Error) *FetchUserByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fetch user by Id bad request response
func (o *FetchUserByIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FetchUserByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FetchUserByIDInternalServerErrorCode is the HTTP code returned for type FetchUserByIDInternalServerError
const FetchUserByIDInternalServerErrorCode int = 500

/*FetchUserByIDInternalServerError Внутреняя ошибка сервера

swagger:response fetchUserByIdInternalServerError
*/
type FetchUserByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFetchUserByIDInternalServerError creates FetchUserByIDInternalServerError with default headers values
func NewFetchUserByIDInternalServerError() *FetchUserByIDInternalServerError {

	return &FetchUserByIDInternalServerError{}
}

// WithPayload adds the payload to the fetch user by Id internal server error response
func (o *FetchUserByIDInternalServerError) WithPayload(payload *models.Error) *FetchUserByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fetch user by Id internal server error response
func (o *FetchUserByIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FetchUserByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FetchUserByIDDefault Неожиданная ошибка

swagger:response fetchUserByIdDefault
*/
type FetchUserByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFetchUserByIDDefault creates FetchUserByIDDefault with default headers values
func NewFetchUserByIDDefault(code int) *FetchUserByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &FetchUserByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the fetch user by ID default response
func (o *FetchUserByIDDefault) WithStatusCode(code int) *FetchUserByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the fetch user by ID default response
func (o *FetchUserByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the fetch user by ID default response
func (o *FetchUserByIDDefault) WithPayload(payload *models.Error) *FetchUserByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fetch user by ID default response
func (o *FetchUserByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FetchUserByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
