// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/i-iterbium/cyber-engine/models"
)

// UpdateUserByIDOKCode is the HTTP code returned for type UpdateUserByIDOK
const UpdateUserByIDOKCode int = 200

/*UpdateUserByIDOK OK

swagger:response updateUserByIdOK
*/
type UpdateUserByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewUpdateUserByIDOK creates UpdateUserByIDOK with default headers values
func NewUpdateUserByIDOK() *UpdateUserByIDOK {

	return &UpdateUserByIDOK{}
}

// WithPayload adds the payload to the update user by Id o k response
func (o *UpdateUserByIDOK) WithPayload(payload *models.User) *UpdateUserByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user by Id o k response
func (o *UpdateUserByIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserByIDBadRequestCode is the HTTP code returned for type UpdateUserByIDBadRequest
const UpdateUserByIDBadRequestCode int = 400

/*UpdateUserByIDBadRequest Переданы некорректные данные

swagger:response updateUserByIdBadRequest
*/
type UpdateUserByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateUserByIDBadRequest creates UpdateUserByIDBadRequest with default headers values
func NewUpdateUserByIDBadRequest() *UpdateUserByIDBadRequest {

	return &UpdateUserByIDBadRequest{}
}

// WithPayload adds the payload to the update user by Id bad request response
func (o *UpdateUserByIDBadRequest) WithPayload(payload *models.Error) *UpdateUserByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user by Id bad request response
func (o *UpdateUserByIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserByIDInternalServerErrorCode is the HTTP code returned for type UpdateUserByIDInternalServerError
const UpdateUserByIDInternalServerErrorCode int = 500

/*UpdateUserByIDInternalServerError Внутреняя ошибка сервера

swagger:response updateUserByIdInternalServerError
*/
type UpdateUserByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateUserByIDInternalServerError creates UpdateUserByIDInternalServerError with default headers values
func NewUpdateUserByIDInternalServerError() *UpdateUserByIDInternalServerError {

	return &UpdateUserByIDInternalServerError{}
}

// WithPayload adds the payload to the update user by Id internal server error response
func (o *UpdateUserByIDInternalServerError) WithPayload(payload *models.Error) *UpdateUserByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user by Id internal server error response
func (o *UpdateUserByIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateUserByIDDefault Неожиданная ошибка

swagger:response updateUserByIdDefault
*/
type UpdateUserByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateUserByIDDefault creates UpdateUserByIDDefault with default headers values
func NewUpdateUserByIDDefault(code int) *UpdateUserByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateUserByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update user by ID default response
func (o *UpdateUserByIDDefault) WithStatusCode(code int) *UpdateUserByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update user by ID default response
func (o *UpdateUserByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update user by ID default response
func (o *UpdateUserByIDDefault) WithPayload(payload *models.Error) *UpdateUserByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user by ID default response
func (o *UpdateUserByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
