// Code generated by go-swagger; DO NOT EDIT.

package confirmation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UserConfirmationHandlerFunc turns a function with the right signature into a user confirmation handler
type UserConfirmationHandlerFunc func(UserConfirmationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserConfirmationHandlerFunc) Handle(params UserConfirmationParams) middleware.Responder {
	return fn(params)
}

// UserConfirmationHandler interface for that can handle valid user confirmation params
type UserConfirmationHandler interface {
	Handle(UserConfirmationParams) middleware.Responder
}

// NewUserConfirmation creates a new http.Handler for the user confirmation operation
func NewUserConfirmation(ctx *middleware.Context, handler UserConfirmationHandler) *UserConfirmation {
	return &UserConfirmation{Context: ctx, Handler: handler}
}

/*UserConfirmation swagger:route POST /userconfirmation Confirmation userConfirmation

Подтверждение пользователя

Подтверждение пользователя по коду

*/
type UserConfirmation struct {
	Context *middleware.Context
	Handler UserConfirmationHandler
}

func (o *UserConfirmation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserConfirmationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
