// Code generated by go-swagger; DO NOT EDIT.

package confirmation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/i-iterbium/cyber-engine/models"
)

// NewUserConfirmationParams creates a new UserConfirmationParams object
// no default values defined in spec.
func NewUserConfirmationParams() UserConfirmationParams {

	return UserConfirmationParams{}
}

// UserConfirmationParams contains all the bound params for the user confirmation operation
// typically these are obtained from a http.Request
//
// swagger:parameters UserConfirmation
type UserConfirmationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Данные для подтверждения пользователя
	  Required: true
	  In: body
	*/
	UserConfirmation *models.UserConfirmation
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUserConfirmationParams() beforehand.
func (o *UserConfirmationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UserConfirmation
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("userConfirmation", "body", ""))
			} else {
				res = append(res, errors.NewParseError("userConfirmation", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.UserConfirmation = &body
			}
		}
	} else {
		res = append(res, errors.Required("userConfirmation", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
