// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/i-iterbium/cyber-engine/restapi/operations/sessions"
	"github.com/i-iterbium/cyber-engine/restapi/operations/user_confirmation"
	"github.com/i-iterbium/cyber-engine/restapi/operations/users"
)

// NewCyberEngineAPI creates a new CyberEngine instance
func NewCyberEngineAPI(spec *loads.Document) *CyberEngineAPI {
	return &CyberEngineAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		SessionsCreateSessionHandler: sessions.CreateSessionHandlerFunc(func(params sessions.CreateSessionParams) middleware.Responder {
			return middleware.NotImplemented("operation sessions.CreateSession has not yet been implemented")
		}),
		UsersCreateUserHandler: users.CreateUserHandlerFunc(func(params users.CreateUserParams) middleware.Responder {
			return middleware.NotImplemented("operation users.CreateUser has not yet been implemented")
		}),
		SessionsDeleteSessionHandler: sessions.DeleteSessionHandlerFunc(func(params sessions.DeleteSessionParams) middleware.Responder {
			return middleware.NotImplemented("operation sessions.DeleteSession has not yet been implemented")
		}),
		UsersFetchUserByIDHandler: users.FetchUserByIDHandlerFunc(func(params users.FetchUserByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation users.FetchUserByID has not yet been implemented")
		}),
		UserConfirmationResendCodeHandler: user_confirmation.ResendCodeHandlerFunc(func(params user_confirmation.ResendCodeParams) middleware.Responder {
			return middleware.NotImplemented("operation user_confirmation.ResendCode has not yet been implemented")
		}),
		SessionsUpdateSessionHandler: sessions.UpdateSessionHandlerFunc(func(params sessions.UpdateSessionParams) middleware.Responder {
			return middleware.NotImplemented("operation sessions.UpdateSession has not yet been implemented")
		}),
		UsersUpdateUserByIDHandler: users.UpdateUserByIDHandlerFunc(func(params users.UpdateUserByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation users.UpdateUserByID has not yet been implemented")
		}),
		UserConfirmationUserConfirmationHandler: user_confirmation.UserConfirmationHandlerFunc(func(params user_confirmation.UserConfirmationParams) middleware.Responder {
			return middleware.NotImplemented("operation user_confirmation.UserConfirmation has not yet been implemented")
		}),
	}
}

/*CyberEngineAPI CyberEngine */
type CyberEngineAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// SessionsCreateSessionHandler sets the operation handler for the create session operation
	SessionsCreateSessionHandler sessions.CreateSessionHandler
	// UsersCreateUserHandler sets the operation handler for the create user operation
	UsersCreateUserHandler users.CreateUserHandler
	// SessionsDeleteSessionHandler sets the operation handler for the delete session operation
	SessionsDeleteSessionHandler sessions.DeleteSessionHandler
	// UsersFetchUserByIDHandler sets the operation handler for the fetch user by ID operation
	UsersFetchUserByIDHandler users.FetchUserByIDHandler
	// UserConfirmationResendCodeHandler sets the operation handler for the resend code operation
	UserConfirmationResendCodeHandler user_confirmation.ResendCodeHandler
	// SessionsUpdateSessionHandler sets the operation handler for the update session operation
	SessionsUpdateSessionHandler sessions.UpdateSessionHandler
	// UsersUpdateUserByIDHandler sets the operation handler for the update user by ID operation
	UsersUpdateUserByIDHandler users.UpdateUserByIDHandler
	// UserConfirmationUserConfirmationHandler sets the operation handler for the user confirmation operation
	UserConfirmationUserConfirmationHandler user_confirmation.UserConfirmationHandler
	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *CyberEngineAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *CyberEngineAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *CyberEngineAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *CyberEngineAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *CyberEngineAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *CyberEngineAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *CyberEngineAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the CyberEngineAPI
func (o *CyberEngineAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.SessionsCreateSessionHandler == nil {
		unregistered = append(unregistered, "sessions.CreateSessionHandler")
	}
	if o.UsersCreateUserHandler == nil {
		unregistered = append(unregistered, "users.CreateUserHandler")
	}
	if o.SessionsDeleteSessionHandler == nil {
		unregistered = append(unregistered, "sessions.DeleteSessionHandler")
	}
	if o.UsersFetchUserByIDHandler == nil {
		unregistered = append(unregistered, "users.FetchUserByIDHandler")
	}
	if o.UserConfirmationResendCodeHandler == nil {
		unregistered = append(unregistered, "user_confirmation.ResendCodeHandler")
	}
	if o.SessionsUpdateSessionHandler == nil {
		unregistered = append(unregistered, "sessions.UpdateSessionHandler")
	}
	if o.UsersUpdateUserByIDHandler == nil {
		unregistered = append(unregistered, "users.UpdateUserByIDHandler")
	}
	if o.UserConfirmationUserConfirmationHandler == nil {
		unregistered = append(unregistered, "user_confirmation.UserConfirmationHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *CyberEngineAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *CyberEngineAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *CyberEngineAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *CyberEngineAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *CyberEngineAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *CyberEngineAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the cyber engine API
func (o *CyberEngineAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *CyberEngineAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/sessions"] = sessions.NewCreateSession(o.context, o.SessionsCreateSessionHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users"] = users.NewCreateUser(o.context, o.UsersCreateUserHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/sessions"] = sessions.NewDeleteSession(o.context, o.SessionsDeleteSessionHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{id}"] = users.NewFetchUserByID(o.context, o.UsersFetchUserByIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/userconfirmation"] = user_confirmation.NewResendCode(o.context, o.UserConfirmationResendCodeHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/sessions"] = sessions.NewUpdateSession(o.context, o.SessionsUpdateSessionHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/users/{id}"] = users.NewUpdateUserByID(o.context, o.UsersUpdateUserByIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/userconfirmation"] = user_confirmation.NewUserConfirmation(o.context, o.UserConfirmationUserConfirmationHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *CyberEngineAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *CyberEngineAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *CyberEngineAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *CyberEngineAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *CyberEngineAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
