// Code generated by go-swagger; DO NOT EDIT.

// Package restapi CyberEngine
//
//  CyberEngine
//  Schemes:
//    http
//  Host: localhost:65433
//  BasePath: /api/v1
//  Version: 1.0.2
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
