// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "CyberEngine",
    "title": "CyberEngine",
    "version": "1.0.2"
  },
  "host": "localhost:65433",
  "basePath": "/api/v1",
  "paths": {
    "/sessions": {
      "post": {
        "description": "Создает пользовательскую сессию",
        "tags": [
          "Sessions"
        ],
        "summary": "Создает пользовательскую сессию",
        "operationId": "createSession",
        "parameters": [
          {
            "description": "Данные для создания сессии",
            "name": "authData",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AuthData"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Сессия успешно создана",
            "schema": {
              "$ref": "#/definitions/Session"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Удаляет пользовательскую сессию",
        "tags": [
          "Sessions"
        ],
        "summary": "Удаляет пользовательскую сессию",
        "operationId": "deleteSession",
        "responses": {
          "200": {
            "description": "Сессия успешно удалена"
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "description": "Обновляет пользовательскую сессию",
        "tags": [
          "Sessions"
        ],
        "summary": "Обновляет пользовательскую сессию",
        "operationId": "updateSession",
        "responses": {
          "200": {
            "description": "Сессия успешно обновлена",
            "schema": {
              "$ref": "#/definitions/Session"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/userconfirmation": {
      "post": {
        "description": "Подтверждение пользователя по коду",
        "tags": [
          "UserConfirmation"
        ],
        "summary": "Подтверждение пользователя",
        "operationId": "userConfirmation",
        "parameters": [
          {
            "description": "Данные для подтверждения пользователя",
            "name": "userConfirmation",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserConfirmation"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Пользователь подтвержден"
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "description": "Отправка кода подтверждения",
        "tags": [
          "UserConfirmation"
        ],
        "summary": "Отправка кода подтверждения",
        "operationId": "resendCode",
        "parameters": [
          {
            "description": "Данные для подтверждения пользователя",
            "name": "resendCode",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserConfirmation"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Код выслан"
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "description": "Cоздает нового пользователя и возвращает его данные",
        "tags": [
          "Users"
        ],
        "summary": "Создает нового пользователя",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "Данные для создания пользователя",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Переданы некорректные данные",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "description": "Возвращает данные пользователя по ID",
        "tags": [
          "Users"
        ],
        "summary": "Возвращает данные пользователя по ID.",
        "operationId": "fetchUserByID",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Идентификатор пользователя",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Переданы некорректные данные",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "description": "Изменяет данные пользователя по ID",
        "tags": [
          "Users"
        ],
        "summary": "Изменяет данные пользователя по ID.",
        "operationId": "updateUserByID",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Идентификатор пользователя",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Данные для изменения пользователя",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EditUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Переданы некорректные данные",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AuthData": {
      "description": "Модель данных новой сессии",
      "properties": {
        "email": {
          "description": "Электронная почта",
          "type": "string",
          "format": "email",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"email\"",
          "x-nullable": true,
          "example": "email@mail.ru"
        },
        "password": {
          "description": "Пароль",
          "type": "string",
          "minLength": 6,
          "x-go-custom-tag": "sql:\"password\"",
          "x-nullable": true,
          "example": "qwerty123"
        },
        "phone": {
          "description": "Номер телефона",
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "sql:\"phone\"",
          "x-nullable": true,
          "example": 79110007777
        }
      }
    },
    "BasicUser": {
      "description": "Пользователь",
      "properties": {
        "birthday": {
          "description": "Дата рождения",
          "type": "string",
          "format": "date",
          "x-go-custom-tag": "sql:\"birthday\"",
          "x-nullable": true,
          "example": "2020-09-21"
        },
        "email": {
          "description": "Адрес электронной почты",
          "type": "string",
          "format": "email",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"email\"",
          "x-nullable": true,
          "example": "email@mail.ru"
        },
        "name": {
          "description": "Имя",
          "type": "string",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"name\"",
          "x-nullable": true,
          "example": "Иван"
        },
        "phone": {
          "description": "Номер телефона",
          "type": "integer",
          "format": "int64",
          "maximum": 79999999999,
          "minimum": 79000000001,
          "x-go-custom-tag": "sql:\"phone\"",
          "x-nullable": true,
          "example": 79876543210
        },
        "pname": {
          "description": "Отчество",
          "type": "string",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"pname\"",
          "x-nullable": true,
          "example": "Иванович"
        },
        "role": {
          "description": "Роль пользователя",
          "type": "string",
          "x-go-custom-tag": "sql:\"role\"",
          "x-nullable": true
        },
        "sname": {
          "description": "Фамилия",
          "type": "string",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"sname\"",
          "x-nullable": true,
          "example": "Иванов"
        }
      }
    },
    "EditUser": {
      "description": "Данные для изменения пользователя",
      "allOf": [
        {
          "$ref": "#/definitions/BasicUser"
        },
        {
          "type": "object"
        }
      ]
    },
    "Error": {
      "description": "Модель ошибки",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "description": "Код ошибки",
          "type": "integer",
          "format": "int64",
          "example": 1001
        },
        "message": {
          "description": "Текст ошибки",
          "type": "string",
          "example": "Запрашиваемый ресурс не найден"
        }
      }
    },
    "NewUser": {
      "description": "Данные для создания пользователя",
      "allOf": [
        {
          "$ref": "#/definitions/BasicUser"
        },
        {
          "type": "object",
          "required": [
            "password",
            "registerType"
          ],
          "properties": {
            "password": {
              "description": "Пароль пользователя\n",
              "type": "string",
              "x-go-custom-tag": "sql:\"password\"",
              "x-nullable": true,
              "example": "qwerty123"
            },
            "registerType": {
              "description": "Способ регистрации\n* phone - по номеру телефона * email  - по адресу электронной почты\n",
              "type": "string",
              "enum": [
                "phone",
                "email"
              ],
              "x-go-custom-tag": "sql:\"register_type\"",
              "example": "phone"
            }
          }
        }
      ]
    },
    "Session": {
      "description": "Модель сессии",
      "properties": {
        "CRSFToken": {
          "description": "CRSF-токен",
          "type": "string",
          "maxLength": 32,
          "minLength": 32,
          "x-go-custom-tag": "sql:\"csrf_token\"",
          "x-nullable": true,
          "example": "1c56b7c4db7d46f985f4aaf154fffdfe"
        },
        "lifeTime": {
          "description": "Срок действия",
          "type": "string",
          "format": "date-time",
          "x-go-custom-tag": "sql:\"life_time\"",
          "x-nullable": true,
          "example": "2020-05-18"
        },
        "session": {
          "description": "Сессия",
          "type": "string",
          "maxLength": 32,
          "minLength": 32,
          "x-go-custom-tag": "sql:\"session\"",
          "x-nullable": true,
          "example": "1c56b7c4db7d46f985f4aaf154fffdfe"
        },
        "userID": {
          "description": "Идентификатор пользователя",
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "sql:\"user_id\"",
          "x-nullable": true,
          "example": 1
        }
      }
    },
    "User": {
      "description": "Пользователь",
      "allOf": [
        {
          "$ref": "#/definitions/BasicUser"
        },
        {
          "type": "object",
          "required": [
            "ID",
            "status"
          ],
          "properties": {
            "ID": {
              "description": "Идентификатор",
              "type": "integer",
              "x-go-custom-tag": "sql:\"id\"",
              "example": 1
            },
            "status": {
              "description": "Статус пользователя\n* new - новый * active  - активный * blocked  - заблокированный\n",
              "type": "string",
              "enum": [
                "active",
                "blocked"
              ],
              "x-go-custom-tag": "sql:\"status\"",
              "x-nullable": true,
              "example": "active"
            },
            "timeout": {
              "description": "Тайм-аут для кода подтверждения регистрации",
              "type": "integer",
              "x-go-custom-tag": "sql:\"timeout\"",
              "example": 1
            }
          }
        }
      ]
    },
    "UserConfirmation": {
      "description": "Данные для подтверждения пользователя",
      "allOf": [
        {
          "type": "object",
          "required": [
            "confirmationType"
          ],
          "properties": {
            "code": {
              "description": "Код подтверждения\n",
              "type": "string",
              "x-go-custom-tag": "sql:\"code\"",
              "x-nullable": true,
              "example": "56744l"
            },
            "confirmationType": {
              "description": "Тип подтверждения\n* phone - по номеру телефона * email  - по адресу электронной почты\n",
              "type": "string",
              "enum": [
                "phone",
                "email"
              ],
              "x-go-custom-tag": "sql:\"register_type\"",
              "example": "phone"
            },
            "email": {
              "description": "Адрес электронной почты",
              "type": "string",
              "format": "email",
              "maxLength": 50,
              "x-go-custom-tag": "sql:\"email\"",
              "x-nullable": true,
              "example": "email@mail.ru"
            },
            "phone": {
              "description": "Номер телефона",
              "type": "integer",
              "format": "int64",
              "maximum": 79999999999,
              "minimum": 79000000001,
              "x-go-custom-tag": "sql:\"phone\"",
              "x-nullable": true,
              "example": 79876543210
            }
          }
        }
      ]
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "CyberEngine",
    "title": "CyberEngine",
    "version": "1.0.2"
  },
  "host": "localhost:65433",
  "basePath": "/api/v1",
  "paths": {
    "/sessions": {
      "post": {
        "description": "Создает пользовательскую сессию",
        "tags": [
          "Sessions"
        ],
        "summary": "Создает пользовательскую сессию",
        "operationId": "createSession",
        "parameters": [
          {
            "description": "Данные для создания сессии",
            "name": "authData",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AuthData"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Сессия успешно создана",
            "schema": {
              "$ref": "#/definitions/Session"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Удаляет пользовательскую сессию",
        "tags": [
          "Sessions"
        ],
        "summary": "Удаляет пользовательскую сессию",
        "operationId": "deleteSession",
        "responses": {
          "200": {
            "description": "Сессия успешно удалена"
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "description": "Обновляет пользовательскую сессию",
        "tags": [
          "Sessions"
        ],
        "summary": "Обновляет пользовательскую сессию",
        "operationId": "updateSession",
        "responses": {
          "200": {
            "description": "Сессия успешно обновлена",
            "schema": {
              "$ref": "#/definitions/Session"
            }
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/userconfirmation": {
      "post": {
        "description": "Подтверждение пользователя по коду",
        "tags": [
          "UserConfirmation"
        ],
        "summary": "Подтверждение пользователя",
        "operationId": "userConfirmation",
        "parameters": [
          {
            "description": "Данные для подтверждения пользователя",
            "name": "userConfirmation",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserConfirmation"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Пользователь подтвержден"
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "description": "Отправка кода подтверждения",
        "tags": [
          "UserConfirmation"
        ],
        "summary": "Отправка кода подтверждения",
        "operationId": "resendCode",
        "parameters": [
          {
            "description": "Данные для подтверждения пользователя",
            "name": "resendCode",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserConfirmation"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Код выслан"
          },
          "400": {
            "description": "Некорректный запрос",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданнная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "description": "Cоздает нового пользователя и возвращает его данные",
        "tags": [
          "Users"
        ],
        "summary": "Создает нового пользователя",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "Данные для создания пользователя",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Переданы некорректные данные",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "description": "Возвращает данные пользователя по ID",
        "tags": [
          "Users"
        ],
        "summary": "Возвращает данные пользователя по ID.",
        "operationId": "fetchUserByID",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Идентификатор пользователя",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Переданы некорректные данные",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "description": "Изменяет данные пользователя по ID",
        "tags": [
          "Users"
        ],
        "summary": "Изменяет данные пользователя по ID.",
        "operationId": "updateUserByID",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Идентификатор пользователя",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Данные для изменения пользователя",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EditUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Переданы некорректные данные",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Внутреняя ошибка сервера",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "default": {
            "description": "Неожиданная ошибка",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AuthData": {
      "description": "Модель данных новой сессии",
      "properties": {
        "email": {
          "description": "Электронная почта",
          "type": "string",
          "format": "email",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"email\"",
          "x-nullable": true,
          "example": "email@mail.ru"
        },
        "password": {
          "description": "Пароль",
          "type": "string",
          "minLength": 6,
          "x-go-custom-tag": "sql:\"password\"",
          "x-nullable": true,
          "example": "qwerty123"
        },
        "phone": {
          "description": "Номер телефона",
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "sql:\"phone\"",
          "x-nullable": true,
          "example": 79110007777
        }
      }
    },
    "BasicUser": {
      "description": "Пользователь",
      "properties": {
        "birthday": {
          "description": "Дата рождения",
          "type": "string",
          "format": "date",
          "x-go-custom-tag": "sql:\"birthday\"",
          "x-nullable": true,
          "example": "2020-09-21"
        },
        "email": {
          "description": "Адрес электронной почты",
          "type": "string",
          "format": "email",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"email\"",
          "x-nullable": true,
          "example": "email@mail.ru"
        },
        "name": {
          "description": "Имя",
          "type": "string",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"name\"",
          "x-nullable": true,
          "example": "Иван"
        },
        "phone": {
          "description": "Номер телефона",
          "type": "integer",
          "format": "int64",
          "maximum": 79999999999,
          "minimum": 79000000001,
          "x-go-custom-tag": "sql:\"phone\"",
          "x-nullable": true,
          "example": 79876543210
        },
        "pname": {
          "description": "Отчество",
          "type": "string",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"pname\"",
          "x-nullable": true,
          "example": "Иванович"
        },
        "role": {
          "description": "Роль пользователя",
          "type": "string",
          "x-go-custom-tag": "sql:\"role\"",
          "x-nullable": true
        },
        "sname": {
          "description": "Фамилия",
          "type": "string",
          "maxLength": 50,
          "x-go-custom-tag": "sql:\"sname\"",
          "x-nullable": true,
          "example": "Иванов"
        }
      }
    },
    "EditUser": {
      "description": "Данные для изменения пользователя",
      "allOf": [
        {
          "$ref": "#/definitions/BasicUser"
        },
        {
          "$ref": "#/definitions/EditUserAllOf1"
        }
      ]
    },
    "EditUserAllOf1": {
      "type": "object"
    },
    "Error": {
      "description": "Модель ошибки",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "description": "Код ошибки",
          "type": "integer",
          "format": "int64",
          "example": 1001
        },
        "message": {
          "description": "Текст ошибки",
          "type": "string",
          "example": "Запрашиваемый ресурс не найден"
        }
      }
    },
    "NewUser": {
      "description": "Данные для создания пользователя",
      "allOf": [
        {
          "$ref": "#/definitions/BasicUser"
        },
        {
          "type": "object",
          "required": [
            "password",
            "registerType"
          ],
          "properties": {
            "password": {
              "description": "Пароль пользователя\n",
              "type": "string",
              "x-go-custom-tag": "sql:\"password\"",
              "x-nullable": true,
              "example": "qwerty123"
            },
            "registerType": {
              "description": "Способ регистрации\n* phone - по номеру телефона * email  - по адресу электронной почты\n",
              "type": "string",
              "enum": [
                "phone",
                "email"
              ],
              "x-go-custom-tag": "sql:\"register_type\"",
              "example": "phone"
            }
          }
        }
      ]
    },
    "Session": {
      "description": "Модель сессии",
      "properties": {
        "CRSFToken": {
          "description": "CRSF-токен",
          "type": "string",
          "maxLength": 32,
          "minLength": 32,
          "x-go-custom-tag": "sql:\"csrf_token\"",
          "x-nullable": true,
          "example": "1c56b7c4db7d46f985f4aaf154fffdfe"
        },
        "lifeTime": {
          "description": "Срок действия",
          "type": "string",
          "format": "date-time",
          "x-go-custom-tag": "sql:\"life_time\"",
          "x-nullable": true,
          "example": "2020-05-18"
        },
        "session": {
          "description": "Сессия",
          "type": "string",
          "maxLength": 32,
          "minLength": 32,
          "x-go-custom-tag": "sql:\"session\"",
          "x-nullable": true,
          "example": "1c56b7c4db7d46f985f4aaf154fffdfe"
        },
        "userID": {
          "description": "Идентификатор пользователя",
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "sql:\"user_id\"",
          "x-nullable": true,
          "example": 1
        }
      }
    },
    "User": {
      "description": "Пользователь",
      "allOf": [
        {
          "$ref": "#/definitions/BasicUser"
        },
        {
          "type": "object",
          "required": [
            "ID",
            "status"
          ],
          "properties": {
            "ID": {
              "description": "Идентификатор",
              "type": "integer",
              "x-go-custom-tag": "sql:\"id\"",
              "example": 1
            },
            "status": {
              "description": "Статус пользователя\n* new - новый * active  - активный * blocked  - заблокированный\n",
              "type": "string",
              "enum": [
                "active",
                "blocked"
              ],
              "x-go-custom-tag": "sql:\"status\"",
              "x-nullable": true,
              "example": "active"
            },
            "timeout": {
              "description": "Тайм-аут для кода подтверждения регистрации",
              "type": "integer",
              "x-go-custom-tag": "sql:\"timeout\"",
              "example": 1
            }
          }
        }
      ]
    },
    "UserConfirmation": {
      "description": "Данные для подтверждения пользователя",
      "allOf": [
        {
          "type": "object",
          "required": [
            "confirmationType"
          ],
          "properties": {
            "code": {
              "description": "Код подтверждения\n",
              "type": "string",
              "x-go-custom-tag": "sql:\"code\"",
              "x-nullable": true,
              "example": "56744l"
            },
            "confirmationType": {
              "description": "Тип подтверждения\n* phone - по номеру телефона * email  - по адресу электронной почты\n",
              "type": "string",
              "enum": [
                "phone",
                "email"
              ],
              "x-go-custom-tag": "sql:\"register_type\"",
              "example": "phone"
            },
            "email": {
              "description": "Адрес электронной почты",
              "type": "string",
              "format": "email",
              "maxLength": 50,
              "x-go-custom-tag": "sql:\"email\"",
              "x-nullable": true,
              "example": "email@mail.ru"
            },
            "phone": {
              "description": "Номер телефона",
              "type": "integer",
              "format": "int64",
              "maximum": 79999999999,
              "minimum": 79000000001,
              "x-go-custom-tag": "sql:\"phone\"",
              "x-nullable": true,
              "example": 79876543210
            }
          }
        }
      ]
    }
  }
}`))
}
