// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/i-iterbium/cyber-engine/models"
)

// NewCreateSessionParams creates a new CreateSessionParams object
// no default values defined in spec.
func NewCreateSessionParams() CreateSessionParams {

	return CreateSessionParams{}
}

// CreateSessionParams contains all the bound params for the create session operation
// typically these are obtained from a http.Request
//
// swagger:parameters createSession
type CreateSessionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Данные для создания сессии
	  Required: true
	  In: body
	*/
	AuthData *models.AuthData
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateSessionParams() beforehand.
func (o *CreateSessionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.AuthData
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("authData", "body", ""))
			} else {
				res = append(res, errors.NewParseError("authData", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.AuthData = &body
			}
		}
	} else {
		res = append(res, errors.Required("authData", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
