// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateSessionHandlerFunc turns a function with the right signature into a create session handler
type CreateSessionHandlerFunc func(CreateSessionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSessionHandlerFunc) Handle(params CreateSessionParams) middleware.Responder {
	return fn(params)
}

// CreateSessionHandler interface for that can handle valid create session params
type CreateSessionHandler interface {
	Handle(CreateSessionParams) middleware.Responder
}

// NewCreateSession creates a new http.Handler for the create session operation
func NewCreateSession(ctx *middleware.Context, handler CreateSessionHandler) *CreateSession {
	return &CreateSession{Context: ctx, Handler: handler}
}

/*CreateSession swagger:route POST /sessions Sessions createSession

Создает пользовательскую сессию

Создает пользовательскую сессию

*/
type CreateSession struct {
	Context *middleware.Context
	Handler CreateSessionHandler
}

func (o *CreateSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateSessionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
