// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/i-iterbium/cyber-engine/models"
)

// CreateSessionOKCode is the HTTP code returned for type CreateSessionOK
const CreateSessionOKCode int = 200

/*CreateSessionOK Сессия успешно создана

swagger:response createSessionOK
*/
type CreateSessionOK struct {

	/*
	  In: Body
	*/
	Payload *models.Session `json:"body,omitempty"`
}

// NewCreateSessionOK creates CreateSessionOK with default headers values
func NewCreateSessionOK() *CreateSessionOK {

	return &CreateSessionOK{}
}

// WithPayload adds the payload to the create session o k response
func (o *CreateSessionOK) WithPayload(payload *models.Session) *CreateSessionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create session o k response
func (o *CreateSessionOK) SetPayload(payload *models.Session) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSessionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSessionBadRequestCode is the HTTP code returned for type CreateSessionBadRequest
const CreateSessionBadRequestCode int = 400

/*CreateSessionBadRequest Некорректный запрос

swagger:response createSessionBadRequest
*/
type CreateSessionBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSessionBadRequest creates CreateSessionBadRequest with default headers values
func NewCreateSessionBadRequest() *CreateSessionBadRequest {

	return &CreateSessionBadRequest{}
}

// WithPayload adds the payload to the create session bad request response
func (o *CreateSessionBadRequest) WithPayload(payload *models.Error) *CreateSessionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create session bad request response
func (o *CreateSessionBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSessionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSessionInternalServerErrorCode is the HTTP code returned for type CreateSessionInternalServerError
const CreateSessionInternalServerErrorCode int = 500

/*CreateSessionInternalServerError Внутреняя ошибка сервера

swagger:response createSessionInternalServerError
*/
type CreateSessionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSessionInternalServerError creates CreateSessionInternalServerError with default headers values
func NewCreateSessionInternalServerError() *CreateSessionInternalServerError {

	return &CreateSessionInternalServerError{}
}

// WithPayload adds the payload to the create session internal server error response
func (o *CreateSessionInternalServerError) WithPayload(payload *models.Error) *CreateSessionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create session internal server error response
func (o *CreateSessionInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSessionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateSessionDefault Неожиданнная ошибка

swagger:response createSessionDefault
*/
type CreateSessionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSessionDefault creates CreateSessionDefault with default headers values
func NewCreateSessionDefault(code int) *CreateSessionDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateSessionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create session default response
func (o *CreateSessionDefault) WithStatusCode(code int) *CreateSessionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create session default response
func (o *CreateSessionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create session default response
func (o *CreateSessionDefault) WithPayload(payload *models.Error) *CreateSessionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create session default response
func (o *CreateSessionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSessionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
