// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSessionHandlerFunc turns a function with the right signature into a delete session handler
type DeleteSessionHandlerFunc func(DeleteSessionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSessionHandlerFunc) Handle(params DeleteSessionParams) middleware.Responder {
	return fn(params)
}

// DeleteSessionHandler interface for that can handle valid delete session params
type DeleteSessionHandler interface {
	Handle(DeleteSessionParams) middleware.Responder
}

// NewDeleteSession creates a new http.Handler for the delete session operation
func NewDeleteSession(ctx *middleware.Context, handler DeleteSessionHandler) *DeleteSession {
	return &DeleteSession{Context: ctx, Handler: handler}
}

/*DeleteSession swagger:route DELETE /sessions Sessions deleteSession

Удаляет пользовательскую сессию

Удаляет пользовательскую сессию

*/
type DeleteSession struct {
	Context *middleware.Context
	Handler DeleteSessionHandler
}

func (o *DeleteSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteSessionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
