// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/i-iterbium/cyber-engine/models"
)

// DeleteSessionOKCode is the HTTP code returned for type DeleteSessionOK
const DeleteSessionOKCode int = 200

/*DeleteSessionOK Сессия успешно удалена

swagger:response deleteSessionOK
*/
type DeleteSessionOK struct {
}

// NewDeleteSessionOK creates DeleteSessionOK with default headers values
func NewDeleteSessionOK() *DeleteSessionOK {

	return &DeleteSessionOK{}
}

// WriteResponse to the client
func (o *DeleteSessionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteSessionBadRequestCode is the HTTP code returned for type DeleteSessionBadRequest
const DeleteSessionBadRequestCode int = 400

/*DeleteSessionBadRequest Некорректный запрос

swagger:response deleteSessionBadRequest
*/
type DeleteSessionBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSessionBadRequest creates DeleteSessionBadRequest with default headers values
func NewDeleteSessionBadRequest() *DeleteSessionBadRequest {

	return &DeleteSessionBadRequest{}
}

// WithPayload adds the payload to the delete session bad request response
func (o *DeleteSessionBadRequest) WithPayload(payload *models.Error) *DeleteSessionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete session bad request response
func (o *DeleteSessionBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSessionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteSessionInternalServerErrorCode is the HTTP code returned for type DeleteSessionInternalServerError
const DeleteSessionInternalServerErrorCode int = 500

/*DeleteSessionInternalServerError Внутреняя ошибка сервера

swagger:response deleteSessionInternalServerError
*/
type DeleteSessionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSessionInternalServerError creates DeleteSessionInternalServerError with default headers values
func NewDeleteSessionInternalServerError() *DeleteSessionInternalServerError {

	return &DeleteSessionInternalServerError{}
}

// WithPayload adds the payload to the delete session internal server error response
func (o *DeleteSessionInternalServerError) WithPayload(payload *models.Error) *DeleteSessionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete session internal server error response
func (o *DeleteSessionInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSessionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteSessionDefault Неожиданнная ошибка

swagger:response deleteSessionDefault
*/
type DeleteSessionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSessionDefault creates DeleteSessionDefault with default headers values
func NewDeleteSessionDefault(code int) *DeleteSessionDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteSessionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete session default response
func (o *DeleteSessionDefault) WithStatusCode(code int) *DeleteSessionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete session default response
func (o *DeleteSessionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete session default response
func (o *DeleteSessionDefault) WithPayload(payload *models.Error) *DeleteSessionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete session default response
func (o *DeleteSessionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSessionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
