// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/i-iterbium/cyber-engine/models"
)

// UpdateSessionOKCode is the HTTP code returned for type UpdateSessionOK
const UpdateSessionOKCode int = 200

/*UpdateSessionOK Сессия успешно обновлена

swagger:response updateSessionOK
*/
type UpdateSessionOK struct {

	/*
	  In: Body
	*/
	Payload *models.Session `json:"body,omitempty"`
}

// NewUpdateSessionOK creates UpdateSessionOK with default headers values
func NewUpdateSessionOK() *UpdateSessionOK {

	return &UpdateSessionOK{}
}

// WithPayload adds the payload to the update session o k response
func (o *UpdateSessionOK) WithPayload(payload *models.Session) *UpdateSessionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update session o k response
func (o *UpdateSessionOK) SetPayload(payload *models.Session) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSessionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSessionBadRequestCode is the HTTP code returned for type UpdateSessionBadRequest
const UpdateSessionBadRequestCode int = 400

/*UpdateSessionBadRequest Некорректный запрос

swagger:response updateSessionBadRequest
*/
type UpdateSessionBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateSessionBadRequest creates UpdateSessionBadRequest with default headers values
func NewUpdateSessionBadRequest() *UpdateSessionBadRequest {

	return &UpdateSessionBadRequest{}
}

// WithPayload adds the payload to the update session bad request response
func (o *UpdateSessionBadRequest) WithPayload(payload *models.Error) *UpdateSessionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update session bad request response
func (o *UpdateSessionBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSessionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSessionInternalServerErrorCode is the HTTP code returned for type UpdateSessionInternalServerError
const UpdateSessionInternalServerErrorCode int = 500

/*UpdateSessionInternalServerError Внутреняя ошибка сервера

swagger:response updateSessionInternalServerError
*/
type UpdateSessionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateSessionInternalServerError creates UpdateSessionInternalServerError with default headers values
func NewUpdateSessionInternalServerError() *UpdateSessionInternalServerError {

	return &UpdateSessionInternalServerError{}
}

// WithPayload adds the payload to the update session internal server error response
func (o *UpdateSessionInternalServerError) WithPayload(payload *models.Error) *UpdateSessionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update session internal server error response
func (o *UpdateSessionInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSessionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateSessionDefault Неожиданнная ошибка

swagger:response updateSessionDefault
*/
type UpdateSessionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateSessionDefault creates UpdateSessionDefault with default headers values
func NewUpdateSessionDefault(code int) *UpdateSessionDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateSessionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update session default response
func (o *UpdateSessionDefault) WithStatusCode(code int) *UpdateSessionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update session default response
func (o *UpdateSessionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update session default response
func (o *UpdateSessionDefault) WithPayload(payload *models.Error) *UpdateSessionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update session default response
func (o *UpdateSessionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSessionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
