// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateSessionHandlerFunc turns a function with the right signature into a update session handler
type UpdateSessionHandlerFunc func(UpdateSessionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSessionHandlerFunc) Handle(params UpdateSessionParams) middleware.Responder {
	return fn(params)
}

// UpdateSessionHandler interface for that can handle valid update session params
type UpdateSessionHandler interface {
	Handle(UpdateSessionParams) middleware.Responder
}

// NewUpdateSession creates a new http.Handler for the update session operation
func NewUpdateSession(ctx *middleware.Context, handler UpdateSessionHandler) *UpdateSession {
	return &UpdateSession{Context: ctx, Handler: handler}
}

/*UpdateSession swagger:route PATCH /sessions Sessions updateSession

Обновляет пользовательскую сессию

Обновляет пользовательскую сессию

*/
type UpdateSession struct {
	Context *middleware.Context
	Handler UpdateSessionHandler
}

func (o *UpdateSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateSessionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
