// Code generated by go-swagger; DO NOT EDIT.

package user_confirmation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/i-iterbium/cyber-engine/models"
)

// ResendCodeOKCode is the HTTP code returned for type ResendCodeOK
const ResendCodeOKCode int = 200

/*ResendCodeOK Код выслан

swagger:response resendCodeOK
*/
type ResendCodeOK struct {
}

// NewResendCodeOK creates ResendCodeOK with default headers values
func NewResendCodeOK() *ResendCodeOK {

	return &ResendCodeOK{}
}

// WriteResponse to the client
func (o *ResendCodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ResendCodeBadRequestCode is the HTTP code returned for type ResendCodeBadRequest
const ResendCodeBadRequestCode int = 400

/*ResendCodeBadRequest Некорректный запрос

swagger:response resendCodeBadRequest
*/
type ResendCodeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewResendCodeBadRequest creates ResendCodeBadRequest with default headers values
func NewResendCodeBadRequest() *ResendCodeBadRequest {

	return &ResendCodeBadRequest{}
}

// WithPayload adds the payload to the resend code bad request response
func (o *ResendCodeBadRequest) WithPayload(payload *models.Error) *ResendCodeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the resend code bad request response
func (o *ResendCodeBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ResendCodeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ResendCodeInternalServerErrorCode is the HTTP code returned for type ResendCodeInternalServerError
const ResendCodeInternalServerErrorCode int = 500

/*ResendCodeInternalServerError Внутреняя ошибка сервера

swagger:response resendCodeInternalServerError
*/
type ResendCodeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewResendCodeInternalServerError creates ResendCodeInternalServerError with default headers values
func NewResendCodeInternalServerError() *ResendCodeInternalServerError {

	return &ResendCodeInternalServerError{}
}

// WithPayload adds the payload to the resend code internal server error response
func (o *ResendCodeInternalServerError) WithPayload(payload *models.Error) *ResendCodeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the resend code internal server error response
func (o *ResendCodeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ResendCodeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ResendCodeDefault Неожиданнная ошибка

swagger:response resendCodeDefault
*/
type ResendCodeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewResendCodeDefault creates ResendCodeDefault with default headers values
func NewResendCodeDefault(code int) *ResendCodeDefault {
	if code <= 0 {
		code = 500
	}

	return &ResendCodeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the resend code default response
func (o *ResendCodeDefault) WithStatusCode(code int) *ResendCodeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the resend code default response
func (o *ResendCodeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the resend code default response
func (o *ResendCodeDefault) WithPayload(payload *models.Error) *ResendCodeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the resend code default response
func (o *ResendCodeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ResendCodeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
