// Code generated by go-swagger; DO NOT EDIT.

package user_confirmation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ResendCodeHandlerFunc turns a function with the right signature into a resend code handler
type ResendCodeHandlerFunc func(ResendCodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ResendCodeHandlerFunc) Handle(params ResendCodeParams) middleware.Responder {
	return fn(params)
}

// ResendCodeHandler interface for that can handle valid resend code params
type ResendCodeHandler interface {
	Handle(ResendCodeParams) middleware.Responder
}

// NewResendCode creates a new http.Handler for the resend code operation
func NewResendCode(ctx *middleware.Context, handler ResendCodeHandler) *ResendCode {
	return &ResendCode{Context: ctx, Handler: handler}
}

/*ResendCode swagger:route PATCH /userconfirmation UserConfirmation resendCode

Отправка кода подтверждения

Отправка кода подтверждения

*/
type ResendCode struct {
	Context *middleware.Context
	Handler ResendCodeHandler
}

func (o *ResendCode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewResendCodeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
