// Code generated by go-swagger; DO NOT EDIT.

package user_confirmation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/i-iterbium/cyber-engine/models"
)

// UserConfirmationOKCode is the HTTP code returned for type UserConfirmationOK
const UserConfirmationOKCode int = 200

/*UserConfirmationOK Пользователь подтвержден

swagger:response userConfirmationOK
*/
type UserConfirmationOK struct {
}

// NewUserConfirmationOK creates UserConfirmationOK with default headers values
func NewUserConfirmationOK() *UserConfirmationOK {

	return &UserConfirmationOK{}
}

// WriteResponse to the client
func (o *UserConfirmationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UserConfirmationBadRequestCode is the HTTP code returned for type UserConfirmationBadRequest
const UserConfirmationBadRequestCode int = 400

/*UserConfirmationBadRequest Некорректный запрос

swagger:response userConfirmationBadRequest
*/
type UserConfirmationBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUserConfirmationBadRequest creates UserConfirmationBadRequest with default headers values
func NewUserConfirmationBadRequest() *UserConfirmationBadRequest {

	return &UserConfirmationBadRequest{}
}

// WithPayload adds the payload to the user confirmation bad request response
func (o *UserConfirmationBadRequest) WithPayload(payload *models.Error) *UserConfirmationBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user confirmation bad request response
func (o *UserConfirmationBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserConfirmationBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserConfirmationInternalServerErrorCode is the HTTP code returned for type UserConfirmationInternalServerError
const UserConfirmationInternalServerErrorCode int = 500

/*UserConfirmationInternalServerError Внутреняя ошибка сервера

swagger:response userConfirmationInternalServerError
*/
type UserConfirmationInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUserConfirmationInternalServerError creates UserConfirmationInternalServerError with default headers values
func NewUserConfirmationInternalServerError() *UserConfirmationInternalServerError {

	return &UserConfirmationInternalServerError{}
}

// WithPayload adds the payload to the user confirmation internal server error response
func (o *UserConfirmationInternalServerError) WithPayload(payload *models.Error) *UserConfirmationInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user confirmation internal server error response
func (o *UserConfirmationInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserConfirmationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UserConfirmationDefault Неожиданнная ошибка

swagger:response userConfirmationDefault
*/
type UserConfirmationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUserConfirmationDefault creates UserConfirmationDefault with default headers values
func NewUserConfirmationDefault(code int) *UserConfirmationDefault {
	if code <= 0 {
		code = 500
	}

	return &UserConfirmationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user confirmation default response
func (o *UserConfirmationDefault) WithStatusCode(code int) *UserConfirmationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user confirmation default response
func (o *UserConfirmationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user confirmation default response
func (o *UserConfirmationDefault) WithPayload(payload *models.Error) *UserConfirmationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user confirmation default response
func (o *UserConfirmationDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserConfirmationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
