// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// User Пользователь
//
// swagger:model User
type User struct {
	BasicUser

	// Идентификатор
	// Required: true
	ID *int64 `json:"ID" sql:"id"`

	// Статус пользователя
	// * new - новый * active  - активный * blocked  - заблокированный
	//
	// Required: true
	// Enum: [active blocked]
	Status *string `json:"status" sql:"status"`

	// Тайм-аут для кода подтверждения регистрации
	Timeout int64 `json:"timeout,omitempty" sql:"timeout"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *User) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BasicUser
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BasicUser = aO0

	// AO1
	var dataAO1 struct {
		ID *int64 `json:"ID"`

		Status *string `json:"status"`

		Timeout int64 `json:"timeout,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.ID = dataAO1.ID

	m.Status = dataAO1.Status

	m.Timeout = dataAO1.Timeout

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m User) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BasicUser)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		ID *int64 `json:"ID"`

		Status *string `json:"status"`

		Timeout int64 `json:"timeout,omitempty"`
	}

	dataAO1.ID = m.ID

	dataAO1.Status = m.Status

	dataAO1.Timeout = m.Timeout

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BasicUser
	if err := m.BasicUser.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *User) validateID(formats strfmt.Registry) error {

	if err := validate.Required("ID", "body", m.ID); err != nil {
		return err
	}

	return nil
}

var userTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["active","blocked"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userTypeStatusPropEnum = append(userTypeStatusPropEnum, v)
	}
}

// property enum
func (m *User) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, userTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *User) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
