// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserConfirmation Данные для подтверждения пользователя
//
// swagger:model UserConfirmation
type UserConfirmation struct {

	// Код подтверждения
	//
	Code *string `json:"code,omitempty" sql:"code"`

	// Тип подтверждения
	// * phone - по номеру телефона * email  - по адресу электронной почты
	//
	// Required: true
	// Enum: [phone email]
	ConfirmationType *string `json:"confirmationType" sql:"register_type"`

	// Адрес электронной почты
	// Max Length: 50
	// Format: email
	Email *strfmt.Email `json:"email,omitempty" sql:"email"`

	// Номер телефона
	// Maximum: 7.9999999999e+10
	// Minimum: 7.9000000001e+10
	Phone *int64 `json:"phone,omitempty" sql:"phone"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *UserConfirmation) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Code *string `json:"code,omitempty"`

		ConfirmationType *string `json:"confirmationType"`

		Email *strfmt.Email `json:"email,omitempty"`

		Phone *int64 `json:"phone,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.Code = dataAO0.Code

	m.ConfirmationType = dataAO0.ConfirmationType

	m.Email = dataAO0.Email

	m.Phone = dataAO0.Phone

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m UserConfirmation) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		Code *string `json:"code,omitempty"`

		ConfirmationType *string `json:"confirmationType"`

		Email *strfmt.Email `json:"email,omitempty"`

		Phone *int64 `json:"phone,omitempty"`
	}

	dataAO0.Code = m.Code

	dataAO0.ConfirmationType = m.ConfirmationType

	dataAO0.Email = m.Email

	dataAO0.Phone = m.Phone

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this user confirmation
func (m *UserConfirmation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfirmationType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePhone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var userConfirmationTypeConfirmationTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["phone","email"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userConfirmationTypeConfirmationTypePropEnum = append(userConfirmationTypeConfirmationTypePropEnum, v)
	}
}

// property enum
func (m *UserConfirmation) validateConfirmationTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, userConfirmationTypeConfirmationTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UserConfirmation) validateConfirmationType(formats strfmt.Registry) error {

	if err := validate.Required("confirmationType", "body", m.ConfirmationType); err != nil {
		return err
	}

	// value enum
	if err := m.validateConfirmationTypeEnum("confirmationType", "body", *m.ConfirmationType); err != nil {
		return err
	}

	return nil
}

func (m *UserConfirmation) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(m.Email) { // not required
		return nil
	}

	if err := validate.MaxLength("email", "body", string(*m.Email), 50); err != nil {
		return err
	}

	if err := validate.FormatOf("email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UserConfirmation) validatePhone(formats strfmt.Registry) error {

	if swag.IsZero(m.Phone) { // not required
		return nil
	}

	if err := validate.MinimumInt("phone", "body", int64(*m.Phone), 7.9000000001e+10, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("phone", "body", int64(*m.Phone), 7.9999999999e+10, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserConfirmation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserConfirmation) UnmarshalBinary(b []byte) error {
	var res UserConfirmation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
